### PR TITLE
Feature/submit message

### PR DESCRIPTION
**Pull request by ozzievee**
## Description
* Added state variables to hold form status and associated messages on the About and Mentor Pages.
* Added Success and Error Alerts to be displayed on form submission on the About and Mentor Pages.
* About and Mentor Pages now render without the form when form is submitted successfully.

## Related Issue
[ Issue #57 ](https://github.com/Vets-Who-Code/vets-who-code-app/issues/57)

## Motivation and Context
* Prevents duplicate form submissions and informs the user if an error occurs.

## How Has This Been Tested?
* All the code has been tested using the provided testing suite. 
* Manually tested form submissions using a fake gateway to ensure application behavior occurs as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by andrew-t-james** [comment]
@ozzievee Work looks good so far, we need the same work to be completed for the contact us section as well. Once that is complete we can get this merged.

**Comment by ozzievee** [comment]
Thank you for the feedback, I will make those changes and comment when it is ready to be reviewed.

**Comment by ozzievee** [comment]
@andrew-t-james the contact form has been updated and now contains the states and associated behaviors. Please let me know any further changes that need to be made. In the meantime, I will be working on improving the test scores for the pages so that we get above 90% code coverage on each (apply.js, contact.js, mentor.js).

**Comment by andrew-t-james** [comment]
@ozzievee this looks good thanks for all the work you put in on this. 👍

**Pull request merged**
