### PR TITLE
Updated _app.js to include the new image for social media sharing

### PR DESCRIPTION
**Pull request by Cameron-Porter**
## Description
Add in a Graph and Twitter Card image for when the VWC-App is shared via social media.

## Related Issue
#382 

## Motivation and Context
At current, the image block was grayed out when someone would share the VWC-app on social media. This change will lead to a higher value of engagement when our link is shared.

## How Has This Been Tested?
I tested the tags at https://www.opengraph.xyz/url/https%3A%2F%2Fvetswhocode.io/ and input the photo to ensure it would populate.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by andrew-t-james — COMMENTED** [review]
Wasn't able to view images from provided link. Unable to verify this change. Please provide a screen shot or instructions on how to reproduce  this change. Thanks

**Comment by Cameron-Porter** [comment]
@andrew-t-james Wasn't exactly sure how to test seeing the image. So instead I used dev tools and inspected both the web app and my changes. Here you will see that the web app does not have the image property included in the meta tags.
Screen Shot 2022-05-09 at 2 48 42 PM
 However, my changes include the image and alt text properties within the meta tag:
Screen Shot 2022-05-09 at 2 47 29 PM
.

**Comment by Cameron-Porter** [comment]
Also, here is the documentation I referenced when making the image content an array:
Screen Shot 2022-05-09 at 2 44 12 PM

**Comment by andrew-t-james** [comment]
Found the preview deploy is showing the images bases on the li k you provided in the pr comments. See working [here](https://www.opengraph.xyz/url/https%3A%2F%2Fvets-who-code-app-git-cporter-graphcards-vetswhocode-web-app.vercel.app%2F/). Curious if we need to change the size of the image so that displays properly. Thoughts?

**Comment by Cameron-Porter** [comment]
I think we should have the whole image shown vs get cut off. I'll see what the recommended dimensions are and set it as that. Then see how it looks.

**Comment by Cameron-Porter** [comment]
Ok, so I updated the dimensions of the images and it still looked cutoff using that same link we had for testing. I then went to each site and tested on their specific site and the full image shows.
Screen Shot 2022-05-10 at 11 47 51 AM
Screen Shot 2022-05-10 at 11 47 45 AM
Screen Shot 2022-05-10 at 11 47 38 AM

**Comment by andrew-t-james** [comment]
Cloudibary has great options that we can use to resize an optimize the quality and size of images as well. [Api docs](https://cloudinary.com/blog/adaptive_browser_based_image_format_delivery)

**Comment by Cameron-Porter** [comment]
Just went back and tested the images with the https://vets-who-code-fpbw33khw-vetswhocode-web-app.vercel.app deployment. This was the one right before making any sizing adjustments. All images do fully show when using the actual site's test. Want to just remove the dimensions and keep it simple since it works?

Testing URLs:
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fvets-who-code-fpbw33khw-vetswhocode-web-app.vercel.app
https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fvets-who-code-66y7kbhxz-vetswhocode-web-app.vercel.app

**Comment by Cameron-Porter** [comment]
@andrew-t-james what are your thoughts on keeping the pics as is without specifying a h/w? Did you want to still see what cloudinary offered or leave it since they fully display on the test sites provided by the individual platforms?

**Review by andrew-t-james — APPROVED** [review]

**Pull request merged**
