### PR TITLE
Add Netlify to sponsor slider

### PR DESCRIPTION
**Pull request by joneskj55**
## Description

This PR adds the Netlify logo to the SponsorSlider as requested in issue #244.

## Related Issue
This PR addresses issue #244.

## Motivation and Context

Adds Netlify to SponsorSlider

## How Has This Been Tested?

This was tested on my local machine in the browser.
## Screenshots (if appropriate):
netlify-screenshot

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joneskj55** [comment]
I'll redo this as svg as mentioned in the issue.

**Comment by gixxerblade** [comment]
@joneskj55 can you also update the jest snapshot with `yarn test --updateSnapshot`? 
re: https://github.com/Vets-Who-Code/vets-who-code-app#testing
Thank you!

**Comment by joneskj55** [comment]
@gixxerblade I added the svg and updated the snapshot in that 3rd commit. Looks like that was the problem with the test failing.

**Comment by gixxerblade** [comment]
@joneskj55 now that there are seven icons on desktop please update the Carousel base settings to make it seven wide. If not the Netlify logo is left on it's own in the carousel. (see screenshot)
Maybe a ratio of 4:7? Here's the line I'm talking about:
 `slidesToShow={isMobile ? 4 : 6}`
https://github.com/Vets-Who-Code/vets-who-code-app/blob/c9e2aa530515bd1c2e254030bf48a61b6a4451ed/src/components/SponsorSlider/SponsorSlider.js#L123

Thank you so much!

screenshot of netlify carousel

**Comment by joneskj55** [comment]
@gixxerblade That makes sense, will do.

**Comment by joneskj55** [comment]
@gixxerblade Just changed the ratio, now it shows 7 across. I also updated the snapshot.

**Review by gixxerblade — APPROVED** [review]
Thank you again! Your help is very much appreciated.

**Comment by joneskj55** [comment]
Thanks a lot, it is my pleasure!

**Pull request merged**
